version: '3.6'
services:
    mysql:
      image: mysql
      restart: always
      ports:
        - "3306:3306"
      volumes:
        - mysql-data:/home/
        - ./db-init:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: assemblage
        MYSQL_USER: assemblage
        MYSQL_PASSWORD: 12345
    rabbitmq:
      image: rabbitmq:management
      ports:
        - "5672:5672"
        - "15672:15672"    
volumes:
  mysql-data:
    name: mysql-data
