spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assemblage
    username: assemblage
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect